swagger: "2.0"
info:
  version: "1.0.0"
  title: "ParteiDuell Backend"
host: "api.parteiduell.de"
basePath: "/"
schemes:
- "https"
paths:
  /list:
    get:
      summary: Quizfragen abrufen
      produces:
      - "application/json"
      parameters:
      - name: "count"
        in: "query"
        description: "Anzahl der Quizfragen"
        required: false
        type: "number"
        default: 1
      - name: "parties"
        in: "query"
        description: "Angefragte Parteien"
        required: false
        type: "string"
      responses:
        200:
          description: "Ok"
  /allParties:
    get:
      summary: Alle verfügbaren Parteien abrufen
      produces:
      - "application/json"
      responses:
        200:
          description: "Ok"
  /allSources:
    get:
      summary: Alle verfügbaren Datenquellen abrufen
      produces:
      - "application/json"
      responses:
        200:
          description: "Ok"
