swagger: "2.0"
info:
  version: "1.0.0"
  title: "ParteiDuell Backend"
host: "api.parteiduell.de"
basePath: "/"
schemes:
- "https"
paths:
  /list:
    get:
      summary: Quizfragen abrufen
      produces:
      - "application/json"
      parameters:
      - name: "count"
        in: "query"
        description: "Anzahl der Quizfragen"
        required: false
        type: "number"
        default: 1
      responses:
        200:
          description: "Ok"
